const users = [
    { id_user: 1,
        prenom_user: 'albi',
        nom_user: 'rigiton',
        genre: 'm',
        date_naissance: '1999-12-10',
        addresse: 'jjjjjjkkkjjj',
        email: 'rigiton.com',
        mot_de_passe: '1234',
        statut: 'visiteur' },
   { id_user: 2,
     prenom_user: 'al',
     nom_user: 'rion',
     genre: 'm',
     date_naissance: '1999-12-30',
     addresse: 'erjnfern jernf ',
     email: 'rion@g.com',
     mot_de_passe: '1234',
     statut: 'visiteur' },
   { id_user: 3,
     prenom_user: 'irma',
     nom_user: 'partion',
     genre: 'f',
     date_naissance: '1945-12-30',
     addresse: '23 firjswdiknvvvd erjn',
     email: 'prtion@g.com',
     mot_de_passe: '1234',
     statut: 'visiteur' },
   { id_user: 4,
     prenom_user: 'elia',
     nom_user: 'briman',
     genre: 'f',
     date_naissance: '1957-02-03',
     addresse: 'kjfnq3  ebfnri3qubf 3',
     email: 'brimanie@b.com.com',
     mot_de_passe: '1234',
     statut: 'visiteur'
    }
];
export default users;
